#!/bin/sh
ssh ubuntu@ec2-65-0-31-147.ap-south-1.compute.amazonaws.com <<EOF
    cd ~/bitveen-node
    git pull origin production
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v19.8.1
    npm install
    npm install -g nodemon pm2
    pm2 restart ecosystem.config.js
    exit
EOF